# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostOrSomething',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image1', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image2', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image3', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image4', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image5', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image6', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image7', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image8', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image9', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image10', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image11', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image12', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image13', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image14', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image15', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
                ('image16', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
    ]
