# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('not_optimized', '0002_genericmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmodel',
            name='not_optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='genericmodel',
            name='image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
