# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 18:15
from __future__ import unicode_literals

from django.db import migrations
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('not_optimized', '0003_auto_20161014_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodel',
            name='not_optimized_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
