# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('not_optimized', '0004_auto_20161014_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodel',
            name='not_optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
