# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('not_optimized', '0005_auto_20171229_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostorsomething',
            name='not_optimized_image_ignored',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='genericmodel',
            name='not_optimized_image_ignored',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
