# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimized_image', '0002_auto_20160715_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedNotOptimized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.IntegerField()),
                ('url', models.URLField()),
                ('optimized_url', models.URLField()),
            ],
        ),
    ]
