# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimized_image', '0003_optimizednotoptimized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimizednotoptimized',
            old_name='instance',
            new_name='instance_pk',
        ),
        migrations.AddField(
            model_name='optimizednotoptimized',
            name='instance_model',
            field=models.CharField(default='optimized_image.BlogPostOrSomething', max_length=100),
            preserve_default=False,
        ),
    ]
