# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimized_image', '0006_auto_20160715_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostOrSomething',
        ),
    ]
